# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProblemResult',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProblemNo', models.IntegerField()),
                ('Operand1', models.IntegerField()),
                ('Operand2', models.IntegerField()),
                ('Operation', models.CharField(max_length=10)),
                ('AnswerCorrectly', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Problem', models.CharField(max_length=50)),
                ('Score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tests',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Users'),
        ),
        migrations.AddField(
            model_name='individualproblemresult',
            name='TestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Tests'),
        ),
    ]
